on:
    push
jobs:
    image-builder:
        name: Checkout prerequisites and build image
        runs-on: self-hosted
        steps:
            -
                name: Checkout current repo
                uses: actions/checkout@v3
            -
                name: Use the provided Dockerfile to build an image
                run: docker build -t my_image .
            -
                name: List docker images
                run: docker images
    image-runner:
        name: Run the image (jobname)
        runs-on: self-hosted
        needs: image-builder
        steps:
            -
                name: Run the image (stepname)
                run: docker run --rm -t my_image
